//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinNUnitRunner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinNUnitRunner.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is written in C# and native APIs using the Xamarin Platform. It runs unit tests using the NUnit Framework..
        /// </summary>
        internal static string AboutPageLineOne {
            get {
                return ResourceManager.GetString("AboutPageLineOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It shares code with its iOS, Android, and Windows versions..
        /// </summary>
        internal static string AboutPageLineTwo {
            get {
                return ResourceManager.GetString("AboutPageLineTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XamarinNUnitRunner.Resources.nunit_xamarin_logo.png.
        /// </summary>
        internal static string AboutPageLogoImagePath {
            get {
                return ResourceManager.GetString("AboutPageLogoImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about NUnit.
        /// </summary>
        internal static string AboutPageNUnitButton {
            get {
                return ResourceManager.GetString("AboutPageNUnitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about this project.
        /// </summary>
        internal static string AboutPageProjectButton {
            get {
                return ResourceManager.GetString("AboutPageProjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about Xamarin.
        /// </summary>
        internal static string AboutPageXamarinButton {
            get {
                return ResourceManager.GetString("AboutPageXamarinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent element cannot be non-null if the element type is RootFilter..
        /// </summary>
        internal static string ArgumentExceptionForRootFilterElementNullMessage {
            get {
                return ResourceManager.GetString("ArgumentExceptionForRootFilterElementNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The leaf element&apos;s child is not null thus the provided leaf element is not the true leaf element. This may indicate an error in the construction or parsing of the filter..
        /// </summary>
        internal static string ArgumentExceptionLeafElementMessage {
            get {
                return ResourceManager.GetString("ArgumentExceptionLeafElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be null or empty..
        /// </summary>
        internal static string ArgumentExceptionMessageForNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("ArgumentExceptionMessageForNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be null..
        /// </summary>
        internal static string ArgumentNullExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given element type is not supported.{0}.
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionElementTypeEnumMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionElementTypeEnumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be greater than or equal to 0..
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionForLessThanZeroMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionForLessThanZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XamarinNUnitRunner.
        /// </summary>
        internal static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The child element has already been set for this instance..
        /// </summary>
        internal static string InvalidOperationExceptionChildAlreadySetMessage {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionChildAlreadySetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent element&apos;s {0} child was not the same reference as the current node..
        /// </summary>
        internal static string InvalidOperationExceptionFilterBuildChildMismatchMessage {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFilterBuildChildMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent element&apos;s {0} child was null..
        /// </summary>
        internal static string InvalidOperationExceptionFilterBuildChildNullMessage {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFilterBuildChildNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root element type was not the expected type of RootFilter but was instead {0}..
        /// </summary>
        internal static string InvalidOperationExceptionFilterBuildElementTypeEnumMessage {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFilterBuildElementTypeEnumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward traversal will not proceed properly. This may indicate an error in the construction or parsing of the filter..
        /// </summary>
        internal static string InvalidOperationExceptionFilterBuildMessage {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFilterBuildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Tests.
        /// </summary>
        internal static string RunTestsButton {
            get {
                return ResourceManager.GetString("RunTestsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XamarinNUnitRunner.Resources.tab_feed.png.
        /// </summary>
        internal static string TabFeedImagePath {
            get {
                return ResourceManager.GetString("TabFeedImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test not executed..
        /// </summary>
        internal static string TestResultNotExecuted {
            get {
                return ResourceManager.GetString("TestResultNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string TestsPageTitle {
            get {
                return ResourceManager.GetString("TestsPageTitle", resourceCulture);
            }
        }
    }
}
